PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX f: <http://www.semanticweb.org/birdb/ontologies/2025/8/茶#>

# Find Tea that complement Apple Pie but not EarlGrey (Subject to Change!)
SELECT DISTINCT ?tea ?flavour ?aroma
WHERE {
    ?tea rdf:type f:Tea;
        f:goWellWithBakery f:ApplePie;
        f:hasFlavour ?flavour;
        f:hasAroma ?aroma.
    FILTER (?tea != f:EarlGrey)
}