PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX f: <http://www.semanticweb.org/birdb/ontologies/2025/8/茶#>

# Get tea and bakery that go well together and are within budget
SELECT ?tea ?tPrice ?bakery ?bPrice
WHERE {
    ?tea rdf:type f:Tea;
    f:hasIngredient f:GreenTeaLeaf;
    f:hasPrice ?tPrice.
    ?bakery rdf:type f:Bakery;
    f:goWellWithTea ?tea;
    f:hasPrice ?bPrice.
    FILTER (?bPrice + ?tPrice < 120)
}